# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/stockadvisor?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    mail:
        host: smtp.gmail.com
        port: 587
        ## USERNAME/PASSWORD comes from Heroku Cloud config
        username:
        password:
        ## CUSTOMIZATION
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 9e793c5b236ca9fd7b7e46e2fcd8cf90a27e744e
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: stockadvisor@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: stockadvisor
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
            
# ===================================================================
# Stock advisor specific properties
# ===================================================================
# // http://crontab.guru/#0/15_9-17_*_*_MON-FRI
stockadvisor:
             jobs:
               madmoney:
                  #every two hours
                  schedule: "* 30 9,11,13,15 * * MON-FRI"
               stockalert:
                   schedule: "* 30 9-17 * * MON-FRI"
               heartbeat:
                   schedule: "* 0 9,11,13,15,17 * * MON-FRI"
               manualstockentry:
                   schedule: "* 0 9-17 * * MON-FRI"
             mail:
              sendto:
              debug: false